POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNwaWRlciBNYW4iLCJpZCI6IjVjY2RlZmNmOTIwNGU3MWM2ODQzZTM5ZSIsImlhdCI6MTU1NzA2MzkzOH0.8mpnilFq6b0kAgknfkxCQwFVKiLZHJ-VDXQclhDVEtU

{
    "title": "The Dark Forest Theory of the Internet",
    "author": "Yancey Strickler",
    "url": "https://onezero.medium.com/the-dark-forest-theory-of-the-internet-7dc3e68a7cb1"
}